name: fskate
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=20.1.8=h8869778_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.17=h4ee41c1_0
  - pip=25.2=pyhc872135_0
  - python=3.11.13=h19e8193_0
  - readline=8.3=h0b18652_0
  - setuptools=78.1.1=py311hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - cffi==2.0.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - jax==0.8.0
      - jaxlib==0.8.0
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - mediapipe==0.10.14
      - ml-dtypes==0.5.3
      - numpy==2.2.6
      - oneeurofilter==0.2.1
      - opencv-contrib-python==4.12.0.88
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - protobuf==4.25.8
      - pycparser==2.23
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scipy==1.16.3
      - six==1.17.0
      - sounddevice==0.5.3
      - tzdata==2025.2
prefix: /Users/dianasivkova/miniconda3/envs/fskate
